### ISSUE TITLE
Book Text not formatted right

### ISSUE THREAD

**Issue by Ceifeire** [TheIllusiveC4/ConstructsArmory#204]
Hey I may be alone in seeing this but most of the text when I read the armor book goes off the page and makes some of it difficult to read. I know its a minor thing but thought I would bring it to your attention. I can supply pics if that will help

**Comment by TheIllusiveC4** [comment]
Can you reproduce this without other mods, only Construct's Armory and its dependencies?

**Comment by Ceifeire** [comment]
Ok I have tested and it seems a different mod is interfering with it. not sure which one. If i discover which one I can let you know.

**Comment by Jennifercutixx** [comment]
that'll be a gui issue. i get that alot on most of the mods i use. how i fix this issue is making the gui scale to a size that its not going off the book. or just play the game in full screen mode. Full screen mode fixes the issue of the text going off the page for me.

**Comment by Ceifeire** [comment]
So i thought about that too. but it did it at every size and i am playing in fullscreen

**Comment by Jennifercutixx** [comment]
try useing this mod https://www.curseforge.com/minecraft/mc-mods/scalingguis scaling guis.
Might fix your issues because scaling gui can make it so u can make a custom gui. If you are running 1.12.2 if not i would try deleting the configs to the mod and start up the game again. because might be that minecraft isnt detecting the gui scale. If not may be a mod that is conflicting with the gui scale of the book its self

**Comment by Jennifercutixx** [comment]
To Add I had a recent render issues and a gui going off the book and all i did was deleted the (options.txt) & (optionsof.txt) and it reconfiged the gui scales and i set it back to my original gui and the text was no longer off the page and my render issues was fixed. But if u do take this opion i will say u will need to re keybind the keys u set them to in the controlls and if u want ajust the detial settings and others. but to me i wouldn't bother concidering it can mess with mods. ^v^

**Comment by Ceifeire** [comment]
So i tried using the scaling GUIs. great mod. but did not fix the book. I did discover it messed with anothe mod I am using and now or was this way before both books have bad text (tinkers and conarm)

**Comment by Jennifercutixx** [comment]
okies, when u just use the ConstructsArmory  on its own is it fixed? if it is then its a compatibility issue and if not then be a bug with the gui scales of the mod. But tbh i'm rll sure its a mod incapability. because alot of mods can mess with the gui of books.

**Comment by Ceifeire** [comment]
yeah i did a test and it is a compatibility issue. Overall its not a big deal just something I had noticed and wasnt sure what caused it originally. If I ever get around to processing all the mods in here and find the culprit I will relay the info

**Comment by Jennifercutixx** [comment]
okies

**Comment by Jennifercutixx** [comment]
okies

**Comment by nikoptune** [comment]
100% the culprit is OptiFine (similar issue happens with Tinkers' Construct books). A workaround is to install the SmoothFont mod and change the font off the default Minecraft font. SmoothFont detects the text rendering method that OptiFine uses & overrides it with it's own, which in turn fixes the text in the books.

**Comment by nikoptune** [comment]
![image](https://user-images.githubusercontent.com/34873184/79520805-835b8f00-800c-11ea-91ff-8f5830cd0aba.png)
Here's how it looks with SmoothFont + Optifine + Construct's Armory (apart of a much larger modpack). No more text running off the page.

**Comment by Ceifeire** [comment]
Ah. Thats interesting. Never would have guessed optifine. I will give that a try when I reinstall optifine.
